### ISSUE TITLE
new IntelliJ compatibility issues

### ISSUE THREAD

**Issue by TiltUp-Rad** [KartanHQ/intellij-nestjs#130]
**Describe the bug**
I just updated my IntelliJ to `2022.3` and got an error about incompatibilities and that it requires IDE build 222.* or earlier

**To Reproduce**
1. Update ur IDE

**Expected behavior**
The plugin works XD

**Screenshots**
![image](https://user-images.githubusercontent.com/116391412/204891513-4b548f1a-3a74-43b1-bc2f-4727d08cbc67.png)

**Comment by TiltUp-Rad** [comment]
<3

**Comment by smith558** [comment]
Same issue now again
