### ISSUE TITLE
Update for support for IntelliJ IDEA 2024.2.0.1

### ISSUE THREAD

**Issue by hildoer** [KartanHQ/intellij-nestjs#383]
### Is your feature request related to a problem? Please describe.

Just updated to the latest IntelliJ and the Nest plugin no longer works.
![Screenshot 2024-08-16 at 13 18 55](https://github.com/user-attachments/assets/e994032d-1716-423c-b284-021a11b48c80)

### Describe the solution you'd like

Make the plugin work again please, and thank you.

**Comment by AcidSlide** [comment]
Why is there no update for this yet?

**Comment by AcidSlide** [comment]
Tik tok.. it's been a month and still not update or confirmation of the issue

**Comment by smith558** [comment]
> Tik tok.. it's been a month and still not update or confirmation of the issue

That's a bit rude. It's a free software. We might need to open a pull request.
