### ISSUE TITLE
Support IntelliJ 2022.2

### ISSUE THREAD

**Issue by Swinkid** [KartanHQ/intellij-nestjs#73]
**Describe the bug**
Plugin is not supported and cannot be enabled on 2022.2.

**To Reproduce**
Install latest 2022.2 and run.

**Expected behavior**
Plugin should enable and work.

**Additional context**
Probably just need to bump the build number - No idea how I'd test since not worked with plugins before. IntelliJ has moved to Java 17 though.

**Comment by nekofar** [comment]
It's going to be available on marketplace in couple of hours.
